sops_secrets:
    domain: ENC[AES256_GCM,data:bGaQbbE5SE2utD2O,iv:3H9eEUinGPIlnqs4qaoXLVPEZB+8HXFVKMdShccyWAw=,tag:GG7x9BIGFEZoVKw6CnmP3A==,type:str]
    letsencrypt_email: ENC[AES256_GCM,data:zb6x+55HpF7JLlMimk+nxlQb7am5,iv:T4DjARIgENukkFtGq3UA59u8rNMwQnyjb8MeDRoJtw0=,tag:f3/Sxl8UhhM+PEEv0i23Rg==,type:str]
    s3_endpoint: ENC[AES256_GCM,data:7SDn/p6iATiI8z3zaeQtCQhSuCEIFSBLbHQvhWnMOQHZQKY=,iv:8463RlpPamkX/sDVBQqbuYtFIZjSN86+g2SraP0Zdt0=,tag:mt0LYJvD1k6BMkWI0no5tA==,type:str]
    s3_bucket: ENC[AES256_GCM,data:SAU5cRrq9g==,iv:TNVxhi+gregGRnYo/15CEF0pro9U689hyMeMI5ZoV4g=,tag:gXGopLZ6DiPW7MBcHqtWRQ==,type:str]
    s3_region: ENC[AES256_GCM,data:pC4UzQ==,iv:cndPNZYMzasN0vcPCSarkUG0yF3EsmrYVKwEdiqbcPs=,tag:GdlgnSM2+3a6JONU7DnsWg==,type:str]
    borg_host: ENC[AES256_GCM,data:gwGZdVZ9oJgX7rakJrZr+4Bt9U5ZHhsPRWo=,iv:3pDiTzK0JrFXFF0f5YqfJ+w02w4mklJNNZJy4S9VT1E=,tag:VoY3jPXa6Ie55bHTkh0ziw==,type:str]
    borg_user: ENC[AES256_GCM,data:pwyc7C2M8g==,iv:0uGQzTGv7utMN395AD2t7ErGc3U5M+hGPSbnN/NtKyc=,tag:EDuWDGNKMZbG4e3xCi6vuQ==,type:str]
    proxy_subnet: ENC[AES256_GCM,data:IZedxz6fivc1Oj9TQg==,iv:MCsy56NSwbSfbYr20Etb/Q20W8S2QT2fzmdC5Q/DRi8=,tag:zqjeoam2R25A4bxmQ1DM1A==,type:str]
    proxy_traefik_ip: ENC[AES256_GCM,data:rLwwVWPiGGRVSg==,iv:svJL0URQlmDOks1aG4qgprze7SWUF6pLZzKpyWZ68Kk=,tag:IKzdxrooGP1bYW7CsBcK0A==,type:str]
    proxy_dns_ip: ENC[AES256_GCM,data:KgNprsbUco9HVKU=,iv:dYf8h3gYmKFvWVU9O5xFwSy6cGrC0V2Vl2znhrE/PdQ=,tag:pob9ANUqXZ3ZIoboYYsRSA==,type:str]
    bootstrap_root_password: ENC[AES256_GCM,data:KkPipUWjWEHry38VOGcfjkKM+bQ=,iv:+/hPBHZxP03/fk/o6HfI4mscKvG54teHoVbfzESXOt0=,tag:gRozi07X31Dzaq3VbURR6g==,type:str]
    hetzner_dns_api_token: ENC[AES256_GCM,data:e2E6iXOjpDZR8jnneH9vUt0vGJ/WxQSRq0WaozVGBlVZtLjAqzf4V6dknCS0jh/O5WFzIsadNUgKpeMgXbl7oQ==,iv:tmgTW3xcd9HVV6OXdZRwZNcVdLHmKmyBKYJY3VQgAs0=,tag:gmTIWxOntnVEGGVz3obW8A==,type:str]
    vps_ipv4: ENC[AES256_GCM,data:GL+S/61sbn5OFfMm2Ss=,iv:6YhG8o5ZLWFPSqgdhQ+GPD9eA56L/X+W6j+ISyngRps=,tag:VE8WMAth3oOeNQz5eky0aA==,type:str]
    vps_ipv6: ENC[AES256_GCM,data:JH21zN3udyp6SVcX20ghsoAlBTiH,iv:wV/1rbQzwA+bbYViUr0XQOK+UnnPd3zAzb6SjJPZ6gA=,tag:IasD1XN8F1+Bq07A/DyRVQ==,type:str]
sops_authentik_secrets:
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:e0cdxcUUhd/4eP3T57TR3fao0k4=,iv:1abww0sd0Lab8qH3y/aOoAYgo7x7vy3ddcvcO7FKPiI=,tag:5B3hc5y29bJcFLwjypufOQ==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:iGkGAwhqgi9pyNbmdPirhhtI7uRs,iv:naDEomh1ovjEMts9hcBRwBxgpd0PYFdUhFEaI6TJ7PQ=,tag:kOSDP4edOrJ7mHmlLXl6kQ==,type:str]
    AUTHENTIK_ADMIN_USERNAME: ENC[AES256_GCM,data:Tghb8K3brg==,iv:Kswieguer8MGPQ8qImmSZ24mpVZh0LtWzg+rCFwvJQ8=,tag:R2ZhyFo8buorpwojBI79tw==,type:str]
    AUTHENTIK_ADMIN_PASSWORD: ENC[AES256_GCM,data:Aks5kWwG4eGhuH1sQxdJ651mIcn3t/0lq5yUo9Ma/sk=,iv:C78BuAVweYuW86FXmWsBquiV5OUL7gE9x6NrMWc8r3k=,tag:ez6adoy3tln3JgN1+aOgJA==,type:str]
    AUTHENTIK_ADMIN_EMAIL: ENC[AES256_GCM,data:yJuX4unEEHnyKIyJyzofb6Udrdjz5Zs0,iv:Z08qg0JXE1tr2LRfOrZan6HnOuO0YTojYiwXUIPxHqY=,tag:W4Lkub/jxY3lhPAxJBJtuQ==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:qwI00yGb5iLqIICg3LXfw1MQIh4+1C5DXBjAVvxNOUGzj2C0YQOvCTF19bfAP+B4jMTIjcBuGSfhUzGIA9XpB+/a2IDD/gPaUmLUyw1qz8E=,iv:U6A6YeHjDeJIcALehxqfPOfVvI4hIfxGouCmzP/6kmU=,tag:uS+603BV1nWIXLj0NacXag==,type:str]
    PG_PASS: ENC[AES256_GCM,data:JS5sD+czOBx9Wufig2pCVdjCXW2fb35jgjQ7rNF6opGB48GnQKg0Bcu7eT1M6iA+,iv:DeBia5vBT06FEBbIjgeEkx9cePzfkwK7PVo0+9uML3E=,tag:iQstAwija+RMpEZGRJ4iQw==,type:str]
    borg_path: ENC[AES256_GCM,data:BqmuJYpAeMlR7Fg=,iv:9u8C0jsM27oqPYoqgtQWbsUKCMP9tun3vi4udQYhKC0=,tag:LpmqHmJKFwRzdSOyenpazg==,type:str]
    borg_passphrase: ENC[AES256_GCM,data:+cGi8x8wg0CrVF/KcBf16YMs6eE7JU3yMFclXRDt0ZyatjxixhH7OzdVJm8=,iv:/mv9RUQmY637E9r5z8tPerNr1v2+pSYYiggK8VROW08=,tag:sFG9O2NiZaKEOBtgItbRqg==,type:str]
sops_reporting_tool_secrets:
    SESSION_SECRET: ENC[AES256_GCM,data:izeKccZQtsErO+z8Sed4vWHrd/HUQ6FRasRQxtAx80NDKtqY7r3Yo6gxBQZighygRjIGknDwz6rZ9naul/UXmQ==,iv:J38NQCCe4TjEuF1CH/96tU/d/Wo/4cvdJOFxoRkqcEY=,tag:tVcEhWnlR+DsiTAf05p3Xw==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:ovEPTqUE4mkhGN+l4oVVPvBMSAE=,iv:7aFmJX1vmtq7zukIGd4AOVrPcnEMckg0YtLqK5qoM3k=,tag:xkVT2WlphoC27aMa41aTag==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:AOSLGTDIvkBtOa5n7tDpJ43aA3np+FzGC9LzQzFZDvbQsr/+SQEc1g==,iv:FWlr2Xq1foey99YCebiMaOsSqInjBgKa53Z+2rtXAtU=,tag:tasynRWCodVvI2f9xefXZA==,type:str]
    borg_path: ENC[AES256_GCM,data:dLzl7UmwTgbKx20oP0OPKg==,iv:lavDNi0KfqlySrnlzCk83yWHCaySbrVRr2VYpge76ZU=,tag:EWK9cyfU7da48ow6988+mg==,type:str]
    borg_passphrase: ENC[AES256_GCM,data:N9nKmenddAI2TXj1RYq0S9tZ6WzuKg9JSP2EJmvwm+g=,iv:Zsq2T0RIshNlVf1MOWYViMjHe4ZvXiCMLS4cRyoMCwI=,tag:FMPX6SMsrUSSgU3unNzr5A==,type:str]
    ADMIN_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:F+qEtm5mByUJIkmJTlkcwBtebTHipjRF6Ng3WEJUArx+HYD36QTXukjB2V1AZthDjkrl1XZ9Jjo1BNepGlNZTg==,iv:Q+pJGjzMpqvA2+KmgLwFV7qT6q7gaooRxNuVojRE+AA=,tag:h066z9geWHxPkRGbxwEMWw==,type:str]
    ADMIN_AUTH_MODE: ENC[AES256_GCM,data:A8imBw==,iv:N2lPF1IS4SNiUwrpVFb+ySrQlO+PnElPChN3PWVC57k=,tag:t0VDO5BIhHE8Bz/kTSqVaA==,type:str]
sops_foundry_secrets:
    FOUNDRY_USERNAME: ENC[AES256_GCM,data:LibfXXkB9tV8b1/Y1oZUPtQ5hmUQ,iv:j5wAlnCGT9yh+8W0SmehrmuuXEAVLNgsYs5mKWE9g/k=,tag:ljM8Awy48lef1DlSXGQPQA==,type:str]
    FOUNDRY_PASSWORD: ENC[AES256_GCM,data:Xirow/MCfnRuxJdhGrYBVRrOArQ1O3QA,iv:8fois9jrxlkfcDe0DgPVHYEyIWhuKAptKFCjnyiQ9+A=,tag:5JERXymf5xoKwRTjCsNNxA==,type:str]
    FOUNDRY_ADMIN_KEY: ENC[AES256_GCM,data:tr6qzO/7GpH0B51+Z8x1ojXhoVPvlTpb,iv:wKPjXXd1gMl/Tsh+nf8x6ge/f+z1sTB7KQ+1yJ1AisI=,tag:jgzwRvFtufYvrhq9tcy7OQ==,type:str]
    borg_path: ENC[AES256_GCM,data:qFVYptGQpdAW,iv:RExNwto9/1qMvIJR8ttVxH61Zs3QPPiTlIIbnx/G5Y0=,tag:GCJtsqeYg/eICeAI5LzSOg==,type:str]
    borg_passphrase: ENC[AES256_GCM,data:sk5ylwX/jCtMHm3vXYHWHcllP6U8pgmNg/J8IPpZlfjdkCDnvmZRLfKiifg=,iv:orYRZNVCiyF/RiRSs07TgtlCiYYwUEGzhR9gpSUUGNo=,tag:RlHs6n1VdHj5VcP8lzNxZQ==,type:str]
sops_conference_tool_secrets:
    SESSION_SECRET: ENC[AES256_GCM,data:Tm0VoNuOUyDfnh+kOBh74yGZcOEtOFVwM4+OisesAFMmBcyha2X7uIXu9h0=,iv:y0qFf9bhlpEg3b7RRTwzTBrGltN93k3e1UbUz7A5a+o=,tag:KCzKN+voxnME9/wehIRZKA==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:M5LQK45pwQ3uPm1kjeRfjv0sM7Q7IiyyISzFcsLWyvcjk8JdAd0K4bw29jo=,iv:pxLTSFqaEmHRFRuVQrnNxRt/zQP6sNYEqHlbIQ23brg=,tag:khuJa4KiiRpnRvkHa1fikg==,type:str]
    borg_path: ENC[AES256_GCM,data:ktcwfDUzpQgonwfUAdpI4c4=,iv:9YSNrpONoMHx75OmMa/WBzyHZwOZTCdbUon0NH3AlHU=,tag:33XcCxqD1xRIRnc1utyk4A==,type:str]
    borg_passphrase: ENC[AES256_GCM,data:NOFF3PEHGSjism0r7iTjkOPzE7MDAXPt8x4ZB7eSNIINOvHhrFk9mJzQsEM=,iv:Bwp57iryoBoiSzrf+KM+PsWR+IU9st/vcAMOH/dnsuY=,tag:zP09J29dc8jAZXx8sdIwNg==,type:str]
sops_n8n_secrets:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:yt0KGN2IkOGqaWHFiHFoIIh3kDSBvHT0sVP1zF6cniwMFQY/ETeT8I+O/YqV9tdEmd24bzjr98rKN1r48u490g==,iv:PcadCgmcFV4HPzxH9m332dzKQq6H5Yu/LkoyTvRf+q4=,tag:J798y12s9KwaFETGkILebg==,type:str]
    N8N_OWNER_EMAIL: ENC[AES256_GCM,data:SbaFoF+gFvY+TTG6h7YMyhcCooclsYHk,iv:3uaSH9X09jmbu4qThlTqKp0guxetZ+XEx46pzSPJ/LQ=,tag:2QYc4c8IgDWp2xLfuQ+FwQ==,type:str]
    N8N_OWNER_PASSWORD: ENC[AES256_GCM,data:h64PWXgbSD6MUSj78hT9rqICJoWKmiBQW3rpr7cABBGcs3im0nYYyHAwikU=,iv:EjgYvFo1/mkss1HJ7/ARlKxK03BazzFSqBefT3fn3uU=,tag:AlRRuFyB3FMStnaoumkhQw==,type:str]
    AUTHENTIK_API_TOKEN: null
    WEBHOOK_SECRET: ENC[AES256_GCM,data:VzvY3+0q2jWFaWreHFcIMxmA4KlCeZ+qRzg18Yb/ZzQcNDrWFtw0Lm6wNBQ=,iv:ac4PoTt7ZiFDWzxFI2dvneX3hpjKr3Galm9/3bE3wyM=,tag:rSYPA86PH+YE3RTJBwrmYg==,type:str]
sops_mail_secrets:
    MAIL_SUBMISSION_PASSWORD: ENC[AES256_GCM,data:/7D8UQShEWD8fzC9c8BZ+bKS/03o7qGKOqhzcy5r7iJWYa+OkA==,iv:e3vhQHFVas0UYRIxNcqVFpEUPyWaeKkh7pI5cL/rs90=,tag:Cc3n4oI3ZGs9dniACZ8i9w==,type:str]
sops_connection:
    ansible_host: ENC[AES256_GCM,data:X9h3F6pj7UwrGXkZkPw=,iv:52gKKx+aC6R/sLO+SRwo+REucriGTaXkWFXDLiZjYvE=,tag:JRxnDIiIgttd5ylMk/U41A==,type:str]
    ansible_become_password: ENC[AES256_GCM,data:5HRVBOXcb3oMwWxvbZ5/uzl6gRI=,iv:3vcPrCpGywWUK2O5WMcVHUR/ISAUpw9yETf3OfV8Vmc=,tag:b5hEI6geE7646h70riYw1w==,type:str]
sops_headscale_secrets:
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:B7DBlru2jnie7Byo9C2KECkMkitU6JQwIRyE3SUf+CsySkSYQ+8t6UvWJkIK0y/4YxLS80kylCPTdzF97QREpw==,iv:okEOVdaOFYvwUp26+n3ooJGOihEosvg9TZIKOmc+TuE=,tag:3YrQl4pylewvfwCGzbpVxA==,type:str]
    borg_path: ENC[AES256_GCM,data:t3f8p9f9m+I2bEM=,iv:ISRPyz9ddaUo0mkBwx1fohgjBjW6SgV5LO8RKZaSgeI=,tag:nKJJa12LPqSVTNWPp/S2xg==,type:str]
    borg_passphrase: ENC[AES256_GCM,data:DoGMfevYxbsHm7/zPdPQ+yaSCx2Q6DIovEriQ9B2nYft60vS6r2dDEO54rY2t/pRwLeyhJxAfPfhPlGemfkSNA==,iv:9j2XHcZHp2cvGYGo8cJZ4BqpC+QSkqPM1enQSb5i4Vg=,tag:obteG91VsAfePgGylE7mFA==,type:str]
sops_ntfy_secrets:
    admin_user: ENC[AES256_GCM,data:W/zA9ng=,iv:K3csN4vIjPX/P5AbVY4VDsieDG853BpcDJXaVhfkAgE=,tag:BO9pfD8+9D/5Lp3XNmOt+Q==,type:str]
    admin_password: ENC[AES256_GCM,data:X/y2mTo0MTVTVXq2hrMjofWHDtX72gO8yOXUjNlnEgI5TKm+u0ni0vACVw==,iv:l8aJlJJOt3d1rf89eqtFrlO6fYzZqUUE+yn2Jrn4tbg=,tag:J8vDZK3wucid6OUHDrIx6Q==,type:str]
    ntfy_tokens:
        - label: ENC[AES256_GCM,data:nzyozdg=,iv:z5eCSi05Oz+KtosXy2tp/C92NFHvp7lZ3AUcl6cg4Ms=,tag:U4Nfjht59aSen2iSUV0KKA==,type:str]
          permissions: ENC[AES256_GCM,data:DPqfoBcRdtHnVA==,iv:orO5UtPnfxM/hcHHl3an6ryCLiRgsCUlEANQlYKm3l0=,tag:us9osBm/IQJemThzE8vffA==,type:str]
        - label: ENC[AES256_GCM,data:9frjYdtTY0XxUA==,iv:4elJwtxEeAG5w97az/CSMkxV2m4q1edFPgtv9yPmZ0k=,tag:s2ytwmEJUH00Bop4CujNcw==,type:str]
          permissions: ENC[AES256_GCM,data:WI9cD7eTImKUAg==,iv:KPqXMCFsONIXtxs5K68n6GhI35VWrASAQryiV9Seal4=,tag:4Bi3gxqnFtyss6OYST8YNA==,type:str]
        - label: ENC[AES256_GCM,data:eU3iJ14eiyg=,iv:8fTXqqyvjNgGNE3sZYSeZHziQOQAa/Qycmx8zF0XJRg=,tag:Lv4IkF/Y7gAxcA+Zdre9rw==,type:str]
          permissions: ENC[AES256_GCM,data:JpJlYWjiqJFVig==,iv:95P9XUxo/MF/CRhKBvB2sJgXm5s4VkaVMnefjsmXgdk=,tag:UH1LE8GCglyNBCNTDEjahg==,type:str]
    ntfy_access:
        - user: ENC[AES256_GCM,data:n4Cd7Uw=,iv:8xYpowe43bpKtxqtLA/VfLw5XP9bCix1eSerBbUWu2s=,tag:WevtG9vq0LKs4oJPBkvuTA==,type:str]
          topic: ENC[AES256_GCM,data:Tg==,iv:kUf22jCAlgx+t98aET1/JccVHjpLvUu4PzrtlpsX1qs=,tag:Qjl/aThb/29mGqsdGm1YpA==,type:str]
          access: ENC[AES256_GCM,data:ZpIj7HDvwg+0OQ==,iv:SyG50IO18diOpuEOJTi6WY8o2tInMTsM3IPiUTN5Ydk=,tag:usBmfV1Oy0s4YmT/OmaH7Q==,type:str]
        - user: ENC[AES256_GCM,data:94COrnE=,iv:dO0kJvfGm2KzOQmExs63dNKq63UYjGzVOgpWiFVTLoU=,tag:Y5Lp0MoQfm3jla/MRGC/4g==,type:str]
          topic: ENC[AES256_GCM,data:nw==,iv:vRjCDJD07ylHVuOIMA1YN1QaLyBO4F06JZFLSmj8YgI=,tag:Bh8RC+yA6wwtdrvQx9ncsA==,type:str]
          access: ENC[AES256_GCM,data:Zm2e1w==,iv:MWTH2Cet7CjXrlpPAtW5cG9UZQF/mA82vlFj5QjtYa0=,tag:ZNzXolKFnlG88G2JYpkusA==,type:str]
    ntfy_users:
        - username: ENC[AES256_GCM,data:S60O5D4=,iv:43WvEJeMLs93dhNRsaYUSE3cFo1ycefFgB2b6ZPy+Ao=,tag:TW6jhB5xXZIBjvYMVOQ+tQ==,type:str]
          password: ENC[AES256_GCM,data:S/C6U1vVFY142AWAXQgZ8IIiAip9f/o/COWb+n8fI5wPyXfacTkfss4LuiI=,iv:lbJqUo07yet0OscGlmaXqF7MNaHAdr7tB3JAqRqqUbQ=,tag:XdOOQ0jfCaYimvpgJJA1EQ==,type:str]
          role: ENC[AES256_GCM,data:AWH//w==,iv:PY+/X/gj73jS0TdLf+ro51QJ6coI7ostrXbIYF/xjGw=,tag:XmIVQcME9XCkWqB9RsIuNQ==,type:str]
sops:
    age:
        - recipient: age1tyq0ywrxqmrk0lssghdqwult6xmzlthqj3kdthu8qqqdpxew840slxmsrg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUFZLbFJvb0ZNbjFDQWE5
            dCtmaHhzU0NkTXdXZnA0K3hMRWZMK3hKZFVzCm00YnpwYmVZaEpZOUZkWG5pY285
            L3MydURqd0xHSmZhTk1WZjQzR21OL1UKLS0tIE9ER0k3clhqTmljTHBXNkRDY0NJ
            aXc5ZEVENzdLTnNhbko1cFBmNks2RmcKVRl/HkZ4C7Y88lf2jhFsELDO3VIYlWn8
            zEzFTR5ZJD6z3UMY8cGnnmnb0ecwvbFJ0flj/+55B6uQTcqJ+rvM7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-12T19:08:03Z"
    mac: ENC[AES256_GCM,data:lTy7prZgvZzXfmHW1vxIACSDBjOT3BMOLkexgqAhUi6hGGTFIiv4PNfWOy804HrWstAqRlzhXeUBT8Mbj1CQFXUfO9BIK+hnm/O4IZDEF587tyee9hiOjhpN14kZm13SFJoYDD6VzEd7EKn40LK7jkEVblvgaF/HHGKgw0o5GR8=,iv:Bi8G/R6iWSg6Rq4fwHlL1R7+HiBKzwlaQT6dURWd/0c=,tag:zwGmnqQ7GsN1+OVYpUX5eg==,type:str]
    pgp:
        - created_at: "2026-07-12T19:08:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA/j3hNQeQwIKAQgAx6N/2l7hAtdZR2EE17/qXs29C7ZWW33lyeOVl3A07MjR
            7VhFZEr2r6zscB/6cQKhnYo2NqvEnJOhwjgnxjfVEw0TwHiImifWQGfKfBkZj+sN
            O7ozZ9BVnxFIoHyhpnDE4wrDmXOdiCnOpYhCyHpIiio944YxknDN6IrQkRk+0pvr
            dcGVYd7SqsvccQCXu70XattYnNLuto1mNbgBEekRtXCbVlmR6vS7kBsFoG3ucjZR
            FfwN9QHiAjZG+6kspJNpiCK4hRs0dD4r8GenGiPCkBOxyITQ/mxx4C1vqviq0BcT
            TxAWYm2cGrDMCmEm/gtY8nZ1qRBMYsZrWwgXL7eZTtJeAf9hat38mgpAguP9YMkg
            RiDgo3Vl9wdwUWZlM7QUKsS4curEYV+bJVjzf8AUdmnHm5KN5T2hoLQ0lAcrb+5c
            lbgKVKbMJScsRXM1bBJ2vV1UxsLDft2ySWgTBVB27g==
            =CiZ7
            -----END PGP MESSAGE-----
          fp: 7D5809CC28C73E4F67AA31398DC23ECC63F6BBA7
    unencrypted_suffix: _unencrypted
    version: 3.12.2
