all:
    hosts:
        vps:
            ansible_host: ENC[AES256_GCM,data:N9ocEvZP4IQ855OSD5k=,iv:OPWuBOidDlgfEog4Y0HUjmTBVyzbvlib0Dvkkca50dE=,tag:z2d7b0CijaQJoLeQuBxFgg==,type:str]
            ansible_user: ENC[AES256_GCM,data:dd/S78Jt,iv:sCejw2MW4yFqIAzU3NDUBadPCWJHcSbGZ+v4ZkUhW7A=,tag:ptL96zUMGCkvdWe3l/qE0w==,type:str]
            ansible_become_method: ENC[AES256_GCM,data:TXE=,iv:sg9f+GRAO1yZm5zWr7wi2bG5+U7V8PFd6gTLNCv2sNk=,tag:8+8r0yKwis4TMNSR0K1gmA==,type:str]
            ansible_become_user: ENC[AES256_GCM,data:JeZRRg==,iv:a3eWRY4GUvcpWsc5LVxYKoxOUgGAiZDvlEp3cXWrioA=,tag:lvSP/tuadp1vYMyiyOJCeA==,type:str]
            ansible_become_password: ENC[AES256_GCM,data:wTlxMBYfJQk5kPew82+q36MrUYw=,iv:lxrVGjmv4faA8GONeB/PwFlsp35+sMT09gGNsVk+kDs=,tag:cx4hLxdWU2uFAu0vQHMIUw==,type:str]
sops:
    age:
        - recipient: age1tyq0ywrxqmrk0lssghdqwult6xmzlthqj3kdthu8qqqdpxew840slxmsrg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUlVRcXcrOEYvSndrb0Z4
            Zm1EYmtJdXRhU0hrbDZ4TEFvYTFhNXM1SVRBCkVsamMzczhUbWJZcy9HRVI5Wk1s
            N0lzZlNCdzhMaUZ4RUpXbHp6UUdnVGsKLS0tIE5BQ09lWU1URlp4ekIvR0g5cGN6
            b3hIVFYwdDZPanJtUmlKYkRVNmVXTDAK91bPGxbhL7uveqMnnEE1RZsCYOVPpIuG
            HK4yZ76KQw0mRHPl0OBIrHKNqvA/oD9nm3VN1b0Nt8MrOsTT7J4UhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T18:36:41Z"
    mac: ENC[AES256_GCM,data:pESGiCNRUV0W//ADRU0dj2NPB5pRugeU5aucIW3U/umOyfH3whWxhzju02C7CBdLhHmpziS71sFnzB0iStMeVcpUwPFNzXJLEeyONIWq2JoVQ2geaEpi5jVHLUFxjmnNFPsrvF//sFZzW0Ijw9Fu/D5m0eGP09Ad1Au8OcjsSLw=,iv:FGgEBJntoBpU7HhzN4ngtS0M5L0Q3TkTlPR0Y4JHxGI=,tag:CRuJfLm6cPNIyjy5WV2eGg==,type:str]
    pgp:
        - created_at: "2026-03-24T12:31:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA/j3hNQeQwIKAQf/ewDShhVb008Aloqve32OyG06+MZ3mQ0BMSaJHYZgU+DL
            wbIeLNMOqJW8yBOwcZ1Xvr+duueQwDb5jlz9ONYD/3JFb+u1QF6PDBR9ZsE9Doxp
            W0hov7jVJ3v3eIo4bW8GtAvahB7XFGwXeW1jnLNU+ZEHtNk63sQNjXWp0cUs6akX
            I8y4y80igM2iY/56bqAyAaxmOeRf10/SRwihwu9/2yeoSnzZdQESMQFjSaBgMAXk
            3bzsCSyCl5rilMz9HpwI8Y96Wu45BjaW0LiqaMWZ55X6V0Jowg+iYUxvAj7Y17HB
            7t5jBkC5f+VPLFy3xPx4+zV8L4tMkfKAD/j/axkno9JcASjZ9IC/zH/zlDg58KwE
            WDR2+1F7CXI2x3tNbjEwKkJIKsy7vR1K/jjIC3PR7QNVAiodPAx6R9GKp4qpF60+
            ywI5CIAjLpNFbJcWsTTAalf0wsM51s1oKeSSTGs=
            =PAEk
            -----END PGP MESSAGE-----
          fp: 7D5809CC28C73E4F67AA31398DC23ECC63F6BBA7
    unencrypted_suffix: _unencrypted
    version: 3.12.2
