---
authentik_version: "2026.2.1"
reporting_tool_admin_oidc_application_slug: "reporting-tool-admin"
reporting_tool_admin_oidc_client_id: "reporting-tool-admin"
reporting_tool_admin_access_group: "reporting-tool-admin-access"
foundry_access_group: "foundry-access"
foundry_proxy_provider_name: "foundry"
foundry_application_slug: "foundry"
conference_tool_oidc_client_id: "conference-tool"
conference_tool_application_slug: "conference-tool"
conference_tool_access_group: "conference-user"
conference_tool_admin_group: "conference-admin"
n8n_proxy_provider_name: "n8n"
n8n_application_slug: "n8n"
n8n_access_group: "n8n-access"
